CREATE TABLE IF NOT EXISTS carta (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    fundo TEXT NOT NULL,
    personagem TEXT NOT NULL,
    borda TEXT NOT NULL,
    atr_for INTEGER NOT NULL,
    atr_des INTEGER NOT NULL,
    atr_con INTEGER NOT NULL,
    atr_int INTEGER NOT NULL,
    atr_sab INTEGER NOT NULL,
    atr_car INTEGER NOT NULL,
    var_for NUMERIC(10,2) NOT NULL,
    var_des NUMERIC(10,2) NOT NULL,
    var_con NUMERIC(10,2) NOT NULL,
    var_int NUMERIC(10,2) NOT NULL,
    var_sab NUMERIC(10,2) NOT NULL,
    var_car NUMERIC(10,2) NOT NULL,
    bonus NUMERIC(10,2) NOT NULL,
    dono INTEGER NOT NULL
);